node:
  build: .
  links:
    - "redis:redis"
    - "mariadb:mariadb"
  environment:
    PORT: "5000"
    NODE_ENV: "production"
    REDIS_URL: "redis://dokku-redis-dataowl:6379"
    DATABASE_URL: "mysql://IamOwl:MaGyf2TNHyvuP4UY@mariadb:3306/dataowl"
  ports:
    - "5000"
redis:
  image: redis
  expose:
    - "6379"
mariadb:
  image: "mariadb:10.1.19"
  environment:
    MYSQL_DATABASE: dataowl
    MYSQL_USER: IamOwl
    MYSQL_PASSWORD: MaGyf2TNHyvuP4UY
    MYSQL_ROOT_PASSWORD: HUIHEWjnefiwuauUIEHFuiiUHIEWFUbeifabiufa
  volumes:
    - "./database:/var/lib/mysql"
  expose:
    - "3306"
