node:
  build: .
  links:
    - "redis:redis"
    - "mariadb:mariadb"
  environment:
    REDIS_URL: "redis://dokku-redis-dataowl:6379"
    DATABASE_URL: "mysql://IamOwl:MaGyf2TNHyvuP4UY@mariadb:3306/dataowl"
redis:
  image: redis
mariadb:
  image: "mariadb:10.1.19"
  environment:
    MYSQL_DATABASE: dataowl
    MYSQL_USER: IamOwl
    MYSQL_PASSWORD: MaGyf2TNHyvuP4UY
    MYSQL_ROOT_PASSWORD: HUIHEWjnefiwuauUIEHFuiiUHIEWFUbeifabiufa
  volumes:
    - "./database:/var/lib/mysql"
nginx:
  image: "nginx:stable"
  volumes:
    - "./web:/usr/share/nginx/deploy:ro"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./nginx/ssl:/etc/ssl"
  links:
    - "node:node"
  ports:
    - "80"
