node:
  build: ./node
  links:
    - "redis:redis"
    - "mariadb:mariadb"
redis:
  image: redis
mariadb:
  image: "mariadb:latest"
  environment:
    MYSQL_DATABASE: dataowl
    MYSQL_USER: IamOwl
    MYSQL_PASSWORD: MaGyf2TNHyvuP4UY
  volumes:
    - "./database:/var/lib/mysql"
nginx:
  image: "nginx:stable"
  volumes:
    - "./web:/usr/share/nginx/deploy:ro"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./nginx/ssl:/etc/ssl"
  links:
    - "node:node"
  ports:
    - "80"
